/**
 * Gère l'affichage et les interactions de la page des favoris
 */

// 1°) REQUÊTER LE BACKEND AVEC LE VERBE "POST", ET AVEC EN PARAMÈTRE BODY DE LA REQUÊTE, À LA CLÉ "favorites" UN ARRAY CONTENANT LES IDs DES ARTICLES MIS EN FAVORIES ({"favorites": getFavorisIDs()}), 
//     AFIN DE RÉCUPÉRER L'ENSEMBLE DES PRODUITS CORRESPONDANTS AUX PRODUITS PRÉSENTS DANS LE localStorage (UTILISER LA FONCTION getFavorisIDs())
// 2°) REFAIRE CE QUI A ÉTÉ FAIT DANS LA PAGE D'ACCUEIL (home/index.js) AFIN D'AFFICHER LES ARTICLES PAR DATE DÉCROISSANTE, ET AVEC LA DATE AFFICHÉ AU FORMAT FR






