/**
 * Gère l'affichage et les interactions de la page des favoris
 */

// 1°) REQUÊTER LE BACKEND AVEC LE VERBE "POST", AFIN DE RÉCUPÉRER L'ENSEMBLE DES PRODUITS CORRESPONDANTS AUX PRODUITS PRÉSENTS DANS LE localStorage (UTILISER LA FONCTION getFavorisIDs())
// 2°) REFAIRE CE QUI A ÉTÉ FAIT DANS LA PAGE D'ACCUEIL (home/index.js) AFIN D'AFFICHER TOUS LES PRODUITS RÉCUPÉRÉS EN 1°) ET DE LES AFFICHER PAR DATE DÉCROISSANTE, AVEC LA DATE AFFICHÉ AU FORMAT FR






